### ISSUE TITLE
Add auth credentials for sentinel

### ISSUE THREAD

**Issue by Smolevich** [lamoda/redis-sentinel#4]
**Feature request**

I suggest to add supporting for auth credentials in config, addd third argument for creating instance `PSRedis\Client` [here](https://github.com/lamoda/redis-sentinel/blob/master/src/RedisLocator.php#L62)

Example:

```
[
        'url' => 'redis-sentinel1:26379; redis-sentinel2:26379',
        'redisName' => 'mastername',
        'username' => 'username',
        'password' => 'password',
]
```

**Comment by scaytrase** [comment]
Partially covered by #5 - added serverauth method with password only
